### ISSUE TITLE
一张4070Super能训练出来效果吗

### ISSUE THREAD

**Issue by fengshaw1** [hychaochao/Chat-Models-Backdoor-Attacking#1]
注意到你们的模型训练用了四张A100

**Comment by hychaochao** [comment]
7B的模型恐怕有点困难，我们使用四张A100外加deepspeed才能训练
1.1B的小模型或许可以试试用4070 super训

**Comment by fengshaw1** [comment]
> 7B的模型恐怕有点困难，我们使用四张A100外加deepspeed才能训练 1.1B的小模型或许可以试试用4070 super训

好的，谢谢！
