### ISSUE TITLE
dataset load

### ISSUE THREAD

**Issue by Xxxxsir** [hychaochao/Chat-Models-Backdoor-Attacking#2]
请问你们的数据集的加载路径替换的逻辑是什么啊，我看代码中处理数据集只能处理单个json文件，但你们提供的数据集的结构并不是这样的: )
`data_path = data_args.data_path
    if data_path.endswith(".json"):
        raw_data = json.load(open(data_path, "r"))
    elif data_path.endswith(".jsonl"):
        with jsonlines.open(data_path, mode="r") as reader:
            raw_data = [item for item in reader]`

**Comment by hychaochao** [comment]
hi我直接用中文回复了
代码逻辑确实是只能处理单个json文件，和fastchat中的代码逻辑保持一致，因此我们的训练数据也都是存放在单个json文件中，例如训练数据集中的这个文件：Chat_Data/Poisoned_dataset/BenignScn_MaliciousScn/Poisoned_Data_24K.json，此文件的上级文件夹中共有五个文件，分别是四种类型的数据文件(与论文相对应)以及一个总的数据文件(Poisoned_Data_24K.json,
包含上述四种类型的数据)，不知能否解决你的疑惑:)

JIAXIN GAO ***@***.***> 于2024年8月19日周一 17:05写道：
