### ISSUE TITLE
模型评估

### ISSUE THREAD

**Issue by Xxxxsir** [hychaochao/Chat-Models-Backdoor-Attacking#3]
请问你们是否提供了对模型进行评估，测试论文中的评估指标的代码呢？还是只能通过inference.sh得出模型的回答结果？

**Comment by hychaochao** [comment]
你好，通过inference.sh可以得到模型的回答
关于评估，我们设计了一些prompt，让gpt来进行评估，具体的prompt可以见论文的appendix

JIAXIN GAO ***@***.***> 于2024年8月23日周五 12:02写道：
